STREAMLIT_SHARING = "true"
REDIRECT_URI = "https://avaniguptaresearch-emailagentstreamlit-srcstreamlit-app-45sbwa.streamlit.app"
AZURE_CLIENT_ID = "7ca1feb4-aaa3-4b19-bd05-ce5de4c23899"
AZURE_CLIENT_SECRET = "2JK8Q~9al3rhAQlWM_qYc5xNRLhcnfWicLy-4bxz"
AZURE_TENANT_ID = "c93272d3-1b07-4b3d-a3b6-19b34a973915"

# LLM Configuration - Use OpenAI API for cloud deployment
OLLAMA_HOST = "https://api.openai.com/v1"
OPENAI_API_KEY = "your-openai-api-key-here"