STREAMLIT_SHARING = "true"
REDIRECT_URI = "https://avaniguptaresearch-emailagentstreamlit-srcstreamlit-app-45sbwa.streamlit.app"

# OpenAI Configuration
OPENAI_API_KEY = "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"

# Azure AD Configuration
AZURE_CLIENT_ID="7ca1feb4-aaa3-4b19-bd05-ce5de4c23899"
AZURE_CLIENT_SECRET="2JK8Q~9al3rhAQlWM_qYc5xNRLhcnfWicLy-4bxZ"
AZURE_TENANT_ID="c93272d3-1b07-4b3d-a3b6-19b34a973915"

# Outlook Agent Configuration
# Copy this file to .env and customize

# Azure AD Configuration
AZURE_CLIENT_ID="7ca1feb4-aaa3-4b19-bd05-ce5de4c23899"
AZURE_CLIENT_SECRET="2JK8Q~9al3rhAQlWM_qYc5xNRLhcnfWicLy-4bxZ"
AZURE_TENANT_ID="c93272d3-1b07-4b3d-a3b6-19b34a973915"

# Model Configuration
MODEL_TYPE=openai

# OpenAI Configuration
OPENAI_API_KEY=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
OPENAI_MODEL=gpt-4o-mini

# Ollama Configuration
OLLAMA_HOST=http://localhost:11434
OLLAMA_MODEL=mistral

# Outlook Configuration
MAX_EMAILS_TO_PROCESS=20
HOURS_BACK_TO_CHECK=24

# Priority Scoring Weights for Outlook
URGENCY_KEYWORD_WEIGHT=15
IMPORTANT_SENDER_WEIGHT=25  
RECENT_EMAIL_BOOST=20
QUESTION_DETECTION_WEIGHT=15
MENTION_DETECTION_WEIGHT=10
OUTLOOK_IMPORTANCE_HIGH_BOOST=30
UNREAD_EMAIL_BOOST=15
ATTACHMENT_BOOST=8

# Agent Behavior
RESPONSE_TEMPERATURE=0.7
MAX_RESPONSE_LENGTH=500
DRAFT_SIGNATURE="Best regards,\n[Your Name]"

# Custom Keywords for Institutional Environment (comma-separated)
CUSTOM_URGENT_KEYWORDS="dean,provost,board meeting,compliance,audit,semester,registration"
CUSTOM_IMPORTANT_SENDERS="dean@university.edu,provost@university.edu,admin@university.edu"