STREAMLIT_SHARING = "true"
REDIRECT_URI = "https://avaniguptaresearch-emailagentstreamlit-srcstreamlit-app-45sbwa.streamlit.app"

# OpenAI Configuration
OPENAI_API_KEY = "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"

# Azure AD Configuration
AZURE_CLIENT_ID = "7ca1feb4-aaa3-4b19-bd05-ce5de4c23899"
AZURE_CLIENT_SECRET = "2JK8Q~9al3rhAQlWM_qYc5xNRLhcnfWicLy-4bxZ"
AZURE_TENANT_ID = "c93272d3-1b07-4b3d-a3b6-19b34a973915"