# Example Streamlit Secrets Configuration
# Copy this to secrets.toml and fill in your actual values

STREAMLIT_SHARING = "true"
REDIRECT_URI = "https://your-streamlit-app-url.streamlit.app"

# Model Configuration
MODEL_TYPE = "openai"

# OpenAI Configuration
OPENAI_API_KEY = "your_openai_api_key_here"
OPENAI_MODEL = "gpt-4o-mini"

# Ollama Configuration (for local use)
OLLAMA_HOST = "http://localhost:11434"
OLLAMA_MODEL = "mistral"

# Azure AD Configuration
AZURE_CLIENT_ID = "your_azure_client_id"
AZURE_CLIENT_SECRET = "your_azure_client_secret"
AZURE_TENANT_ID = "your_azure_tenant_id"

# Outlook Configuration
MAX_EMAILS_TO_PROCESS = 20
HOURS_BACK_TO_CHECK = 24

# Priority Scoring Weights for Outlook
URGENCY_KEYWORD_WEIGHT = 15
IMPORTANT_SENDER_WEIGHT = 25
RECENT_EMAIL_BOOST = 20
QUESTION_DETECTION_WEIGHT = 15
MENTION_DETECTION_WEIGHT = 10
OUTLOOK_IMPORTANCE_HIGH_BOOST = 30
UNREAD_EMAIL_BOOST = 15
ATTACHMENT_BOOST = 8

# Agent Behavior
RESPONSE_TEMPERATURE = 0.7
MAX_RESPONSE_LENGTH = 500
DRAFT_SIGNATURE = """Best regards,
[Your Name]"""

# Custom Keywords for Institutional Environment (comma-separated)
CUSTOM_URGENT_KEYWORDS = "dean,provost,board meeting,compliance,audit,semester,registration"
CUSTOM_IMPORTANT_SENDERS = "dean@university.edu,provost@university.edu,admin@university.edu"

# Logging Configuration
LOG_LEVEL = "INFO"

# Processing Mode Email Limits
ULTRA_LITE_INITIAL_MAX = 5
ULTRA_LITE_EXTENDED_MAX = 8
LITE_INITIAL_MAX = 10
LITE_EXTENDED_MAX = 15
DEEP_INITIAL_MAX = 20
DEEP_EXTENDED_MULTIPLIER = 2